# Generated by Django 3.2.1 on 2021-05-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(help_text='Enter a mark (e. g. fresh)', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(help_text='Enter a unit of measure (e. g. Kg)', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Enter a product type (e. g. fruits)', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('akce', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mark')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.measure')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.type')),
            ],
            options={
                'ordering': ['type', 'name', 'price', 'akce'],
            },
        ),
    ]
